stages:
  default:
    cmd: python -m src.model.train default
    deps:
    - data/test/
    - data/train/
    - data/val/
    - src/const.py
    - src/data/generator.py
    - src/model/arch.py
    - src/model/callbacks.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/default/
  camloss:
    cmd: python -m src.model.train camloss
    deps:
    - data/test/
    - data/train/
    - data/val/
    - src/const.py
    - src/data/generator.py
    - src/model/arch.py
    - src/model/callbacks.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/camloss/
  camloss map:
    cmd: python -m src.data.generator camloss
    deps:
    - data/test/
    - data/train/
    - data/val/
    - models/camloss/
    - src/const.py
    - src/data/generator.py
    - src/model/loss.py
    outs:
    - data/cams/camloss.png
    - data/cams/camloss/
  default map:
    cmd: python -m src.data.generator default
    deps:
    - data/test/
    - data/train/
    - data/val/
    - models/default/
    - src/const.py
    - src/data/generator.py
    - src/model/loss.py
    outs:
    - data/cams/default.png
    - data/cams/default/
