stages:
  tripletloss:
    cmd: python -m src.auxilliary.train clustering
    deps:
    - data/annotations/
    - src/auxilliary/loss.py
    - src/auxilliary/train.py
    - src/const.py
    - src/data/siamese.py
    outs:
    - models/clustering.pt
  default-train:
    cmd: python -m src.model.train default
    deps:
    - data/waterbirds/
    - src/const.py
    - src/data/waterbirds.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/default.pt
  multiloss-train:
    cmd: python -m src.model.train multiloss
    deps:
    - data/waterbirds/
    - models/clustering.pt
    - src/const.py
    - src/data/waterbirds.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/multiloss.pt
  default-visualize:
    cmd: python -m src.model.evaluate visualize default
    deps:
    - data/waterbirds/
    - models/default.pt
    - src/const.py
    - src/data/waterbirds.py
    - src/model/evaluate.py
    outs:
    - data/evals/default.png
  default-group:
    cmd: python -m src.model.evaluate group default
    deps:
    - data/waterbirds/
    - models/default.pt
    - src/const.py
    - src/data/waterbirds.py
    - src/model/evaluate.py
    outs:
    - data/evals/default.txt
  multiloss-visualize:
    cmd: python -m src.model.evaluate visualize multiloss
    deps:
    - data/waterbirds/
    - models/multiloss.pt
    - src/const.py
    - src/data/waterbirds.py
    - src/model/evaluate.py
    outs:
    - data/evals/multiloss.png
  multiloss-group:
    cmd: python -m src.model.evaluate group multiloss
    deps:
    - data/waterbirds/
    - models/multiloss.pt
    - src/const.py
    - src/data/waterbirds.py
    - src/model/evaluate.py
    outs:
    - data/evals/multiloss.txt
